### ISSUE TITLE
Exposures error in tables: TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by patrykkalinowski** [gouline/dbt-metabase#322]
If I build a dbt model with alias config:
```sql
# renamed_example.sql

{{ config(
    alias="example"
)}}
```

Generated exposures will refer to aliased table name instead of original model name:
```sql
 depends_on:
      - ref('example')
```

Which results in error during compilation:
```
Compilation Error
  Exposure 'exposure.xxx.zzz' (models/exposures.yml) depends on a node named 'example' which was not found
```

**Comment by gouline** [comment]
Which version are you using? I thought this was fixed a few months ago. 

Also, what kind of database?

**Comment by patrykkalinowski** [comment]
Oops, my bad! I was indeed using outdated version locally and didn't notice.

Sorry for the confusion.

Still doesn't work for me with another error on 1.5.2, though (removed some successful relation DEBUG rows for clarity):
```
# dbt-metabase exposures --verbose
---
(...)
DEBUG    2025-06-13 23:10:56 +0200 — Relation from 'user_id' to 'dbt_analytics.users.user_id'                                          manifest.py:344
DEBUG    2025-06-13 23:10:56 +0200 — Relation from 'account_id' to 'dbt_analytics.dim_accounts.account_id'
(...)
DEBUG    2025-06-13 23:03:10 +0200 — https://xxx.metabaseapp.com:443 "GET /api/database HTTP/11" 200 None                  connectionpool.py:546
DEBUG    2025-06-13 23:03:10 +0200 — https://xxx.metabaseapp.com:443 "GET /api/table HTTP/11" 200 None

Traceback (most recent call last):
  File "/Users/patryk/.pyenv/versions/3.11.2/bin/dbt-metabase", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/__main__.py", line 189, in wrapper
    return func(
           ^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/__main__.py", line 398, in exposures
    core.extract_exposures(
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/_exposures.py", line 96, in extract_exposures
    table_names={
                ^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/_exposures.py", line 97, in <dictcomp>
    t["id"]: ".".join(
             ^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found
```

We are on Bigquery (dbt v1.9.8 and dbt-bigquery v1.9.2)

We successfully run `models` in production with `--skip-sources` flag, because without it `models` crashes with:
```
Traceback (most recent call last):
  File "/Users/patryk/.pyenv/versions/3.11.2/bin/dbt-metabase", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/__main__.py", line 189, in wrapper
    return func(
           ^^^^^
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/__main__.py", line 320, in models
    core.export_models(
  File "/Users/patryk/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbtmetabase/_models.py", line 124, in export_models
    raise MetabaseStateError("Unable to sync models with Metabase")
dbtmetabase.errors.MetabaseStateError: Unable to sync models with Metabase
```

Maybe this will help if these are connected.

I have renamed the issue for clarity.

**Comment by gouline** [comment]
"Sequence item 0" is database name, so something's up with your BigQuery configuration in Metabase. I don't have BigQuery to test against, you'll have to help me debug this.

What Metabase version are you using?

Go to `https://<YOUR_METABASE_HOST>/api/database` and find the BigQuery database you are attempting to use. Are any of these keys present under the `details` object for that database: `dbname`, `db`, `project-id`, `catalog`? It would be helpful if you post the entire `details` block, redacting any sensitive values but leaving the keys intact.

**Comment by patrykkalinowski** [comment]
OK, looking at `details` object I found the reason.

One of the connections had `project-id: null` and `project-id-from-credentials` with value.
```
"details": {
                "cloud-ip-address-info": null,
                "dataset-filters-type": "inclusion",
                "project-id-from-credentials": "<redacted>",
                "dataset-filters-patterns": "imports",
                "let-user-control-scheduling": true,
                "advanced-options": true,
                "use-jvm-timezone": false,
                "service-account-json": "**MetabasePass**",
                "project-id": null,
                "include-user-id-and-hash": true
            },
```

In connection settings, project ID was empty and inferred from JSON service key.
After manually providing project-id, exposures worked right away.

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/1302cbc4-6672-4769-a44f-a7784778456f" />

I guess you could include `project-id-from-credentials` to the list of fields to account for this case.

Thanks for helping out with this!

**Comment by patrykkalinowski** [comment]
Yes
